spring:
  application:
    name: aitasker

  datasource:
  #  Thay đổi cấu hình kết nối theo môi trường của bạn, lưu ý tạo database AITasker trước khi chạy ứng dụng
    url: jdbc:sqlserver://localhost:1433;databaseName=AITasker;encrypt=false;trustServerCertificate=true 
    username: sa
    password: Aa123456 # Thay đổi mật khẩu này theo cấu hình của bạn 
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: "aitasker-jwt-secret-key-must-be-at-least-32-characters"
    expiration-ms: 86400000