spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    enabled: true

logging:
  level:
    root: WARN
    com.aitasker: INFO
    org.hibernate.SQL: WARN
