package com.aitasker.analytics.enums;

public enum AnalyticsEventType {
    USER_REGISTERED,
    USER_LOGIN,
    JOB_CREATED,
    JOB_CLOSED,
    PROPOSAL_SUBMITTED,
    PROPOSAL_ACCEPTED,
    PROPOSAL_REJECTED,
    PROJECT_STARTED,
    PROJECT_COMPLETED,
    PROJECT_CANCELLED,
    MILESTONE_APPROVED,
    PAYMENT_DEPOSITED,
    PAYMENT_RELEASED,
    PAYMENT_REFUNDED,
    WITHDRAWAL_REQUESTED,
    WITHDRAWAL_APPROVED,
    REVIEW_SUBMITTED,
    AI_PROMPT_USED,
    EXPERT_RECOMMENDED,
    DISPUTE_CREATED,
    DISPUTE_RESOLVED
}