package com.aitasker.security.audit.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    LOGOUT,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PAYMENT_DEPOSITED,
    PAYMENT_RELEASED,
    PAYMENT_REFUNDED,
    DISPUTE_CREATED,
    DISPUTE_RESOLVED,
    ADMIN_USER_BANNED,
    ADMIN_USER_UNBANNED
}
